### PR TITLE
(Fix) Events: stop empty-day “Not found” flicker

### LINKED ISSUE #402: Events load more
**Steps to reproduce**

1. Open events page https://v4.wedance.vip/events
2. Select date **1 October 2026**

**Actual result**

"Not found" block shows and disappears

**Expected result**

"Not found" block shows and doesn't disappear

### PR DESCRIPTION
**Pull request by egemengunel**
Update the events router to add a shared `commonWhere` filter. Same rules (city, style, type, search) in one place, spread into both queries

add next query that actually looks for the earliest future event rather than the next day, stopping the list from flickering in

Fixes #402

### CODE REVIEW

File: server/trpc/routers/events.ts [hunk 1]
```diff
@@ -24,53 +23,45 @@ export const eventsRouter = router({
...
+          ...commonWhere,
+        },
+        orderBy: { startDate: 'asc' },
+        select: { startDate: true },
       })
 
-      const nextDate = addDays(startOfDay, 2)
-      const nextPage = nextDate.toISOString().slice(0, 10)
+      //the legacy constants
+      // const nextDate = addDays(startOfDay, 2)
```
Comment (razbakov) [inline server/trpc/routers/events.ts]: please always remove unused code

**Review by razbakov — CHANGES_REQUESTED** [review]

File: server/trpc/routers/events.ts (hunk 1 above)
Comment (egemengunel) [reply server/trpc/routers/events.ts]: I have removed them in the latest commit.

**Review by razbakov — APPROVED** [review]
